server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: webserviceModule
          uri: lb://XCENTER-WEBSERVICE
          predicates:
            - Path=/webservice/**
        - id: consumerModule
          uri: lb://SECOND-SERVICE
          predicates:
            - Path=/consumer/**